/**
 * Generates the stretch library from the public-domain exercises dataset.
 *
 *   bun run scripts/build-library.ts
 *
 * Pulls every `category: "stretching"` entry, downloads both demo photos,
 * infers per-side vs hold from the instructions text, assigns default time
 * options, and writes:
 *   - assets/stretches/<id>/{0,1}.jpg   (vendored photos)
 *   - src/stretches/library.data.json   (generated content)
 *   - src/stretches/images.ts           (static require map for Metro)
 *
 * Re-run any time to refresh. Photos are Unlicense (public domain).
 */
import { mkdir, readdir, rm, stat, writeFile } from "node:fs/promises";

const DATA_URL = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json";
const IMG_BASE = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";
const ASSETS_DIR = "assets/stretches";

type Raw = {
  id: string;
  name: string;
  category: string;
  primaryMuscles?: string[];
  instructions?: string[];
  images?: string[];
};

// Genuine side-switch language only — deliberately excludes "repeat for N
// reps", which is rep counting, not laterality.
const PER_SIDE = /\b(other|opposite) (leg|side|arm|hand|knee|foot)\b|switch sides?\b|switch to the other|each (side|leg|arm)\b|repeat (on|with|to) the other|on the other (side|leg|arm)\b|both sides\b/i;

const slug = (id: string) =>
  id.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

async function downloadImage(remote: string, dest: string): Promise<boolean> {
  // Reuse already-vendored photos so re-runs (e.g. to retune options) are fast.
  try {
    if ((await stat(dest)).size >= 2000) return true;
  } catch {
    // not downloaded yet
  }
  const res = await fetch(`${IMG_BASE}/${remote}`);
  if (!res.ok) return false;
  const bytes = new Uint8Array(await res.arrayBuffer());
  if (bytes.byteLength < 2000) return false; // guard against error pages
  await writeFile(dest, bytes);
  return true;
}

async function run() {
  console.log("Fetching dataset…");
  const all: Raw[] = await (await fetch(DATA_URL)).json();
  const stretches = all.filter((e) => e.category === "stretching");
  console.log(`Found ${stretches.length} stretching entries.`);

  const data: unknown[] = [];
  const imageEntries: string[] = [];
  const usedIds = new Set<string>();

  // Limited-concurrency processing.
  const queue = [...stretches];
  const workers = Array.from({ length: 8 }, async () => {
    while (queue.length) {
      const e = queue.shift()!;
      const baseId = slug(e.id);

      let id = baseId;
      while (usedIds.has(id)) id += "-x";
      usedIds.add(id);

      const dir = `${ASSETS_DIR}/${id}`;
      await mkdir(dir, { recursive: true });

      const present: number[] = [];
      const remotes = e.images ?? [];
      for (let i = 0; i < remotes.length && i < 2; i++) {
        if (await downloadImage(remotes[i], `${dir}/${i}.jpg`)) present.push(i);
      }

      const text = (e.instructions ?? []).join(" ");
      const perSide = PER_SIDE.test(text);
      const options = perSide
        ? [{ kind: "perSide", secondsPerSide: 30 }, { kind: "perSide", secondsPerSide: 20 }]
        : [{ kind: "hold", seconds: 45 }, { kind: "hold", seconds: 30 }];

      data.push({
        id,
        name: e.name,
        image: id,
        instructions: e.instructions ?? [],
        muscles: e.primaryMuscles ?? [],
        options,
      });

      if (present.length) {
        const reqs = present.map((i) => `require("../../assets/stretches/${id}/${i}.jpg")`).join(", ");
        imageEntries.push(`  "${id}": [${reqs}],`);
      }
    }
  });
  await Promise.all(workers);

  data.sort((a: any, b: any) => a.name.localeCompare(b.name));
  imageEntries.sort();

  await writeFile("src/stretches/library.data.json", JSON.stringify(data, null, 2) + "\n");

  const imagesTs = `// AUTO-GENERATED by scripts/build-library.ts — do not edit.
import type { ImageSourcePropType } from "react-native";

export const stretchImages: Record<string, ImageSourcePropType[]> = {
${imageEntries.join("\n")}
};
`;
  await writeFile("src/stretches/images.ts", imagesTs);

  // Remove photo dirs for entries no longer in the library.
  let removedDirs = 0;
  for (const dir of await readdir(ASSETS_DIR)) {
    if (!usedIds.has(dir)) {
      await rm(`${ASSETS_DIR}/${dir}`, { recursive: true });
      removedDirs++;
    }
  }

  const withImages = imageEntries.length;
  console.log(
    `Wrote ${data.length} stretches (${withImages} with photos) -> library.data.json + images.ts`,
  );
  if (removedDirs) console.log(`Removed ${removedDirs} orphaned photo dirs.`);
}

run();
